# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Antony Jucan
tagline:             'A Github Hosted Website'
description:         'This is a website that lists my major life accomplishments'
url:                 http://lanyon.getpoole.com
baseurl:             '/Website'
paginate:            5

# About/contact
author:
  name:              Antony Jucan
  url:               https://twitter.com/mdo
  email:             ajucan8@gmail.com

# Custom vars
version:             1.0.0

theme: jekyll-theme-slate
