# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Antony Jucan
tagline:             'A Github Hosted Website'
description:         'This is a website that lists my major life accomplishments'
url:                 https://caligula8.github.io
baseurl:             '/Website/'
# The following line is required for Jekyll >=3 support
gems:                [jekyll-paginate, jekyll-gist]
paginate:            5

# About/contact
author:
  name:              Antony Jucan
  url:               https://twitter.com/mdo
  email:             ajucan8@gmail.com

# Custom vars
version:             Lanyon

